server:
    port: 9001
uri:
  api:
    clients: http://localhost:9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestTokens: 1
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/fallback
      routes:
        - id: clients
          uri: ${uri.api.clients}
          predicates:
            - Path=/clients/**
          filters:
            - RewritePath=/clients, /v1/api/clients
            - AddRequestHeader=X-Request-Client, gateway
            - AddResponseHeader=X-Response-Client, gateway
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
# Trace every action
management:
  tracing:
    sampling:
      probability: 1.0